language: go
go:
#  - 1.0
#  - 1.1
  - 1.2
  - tip
script:
  - go get code.google.com/p/go.tools/cmd/cover
  - go install code.google.com/p/go.tools/cmd/cover
  - go test -covermode=count -coverprofile=profile.cov
  - go get github.com/mattn/goveralls
  - go install github.com/mattn/goveralls
  - ../../../../bin/goveralls -coverprofile=profile.cov -service=travis-ci